name: Shuttle Deploy

on:
    schedule:
        - cron: '0 0 */28 * *'
    workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JF90BSDEENEZS33SYZT735GR
