name: Shuttle Deploy

on:
  schedule:
    - cron: "0 0 */28 * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: 8wWEvQ8J3I84KmhO
          project-id: proj_01JF90BSDEENEZS33SYZT735GR
          working-directory: "axum-react-chat-app/backend"
          cargo-shuttle-version: "0.55.0"
          extra-args: --allow-dirty --debug
